### PR TITLE
Change formatting rule for access modifiers

### PR DESCRIPTION
**Pull request by Barthelemy**
1 space before modifer, then 1 more space for the members (total 2 spaces).
O2-24

### CODE REVIEW

**Comment by Barthelemy** [comment]
As discussed some time ago in WP3...

**Comment by awegrzyn** [comment]
Hi Barth,
I think we should enforce all the rules in `clang-format` otherwise it's too complex to keep up with all formatting manually.
Moving to `clang-format`, currently clang-format settings inside this repository != AliceO2 != Monitoring... What I propose is to keep one `.clang-format` config in this repo and fetch it during the build (sorry for offtop).

**Comment by awegrzyn** [comment]
Okay actually this rule already exists in `clang-format`:
```
AccessModifierOffset: -1
```

**Comment by Barthelemy** [comment]
@awegrzyn I agree. Originally the idea was to host the .clang-format in the repo CodingGuidelines. We can store it instead in AliceO2 and pull it from other repos, I don't mind. 
I know very little about pulling stuff from other repos. Is there a way to do it automatically ?

**Comment by Barthelemy** [comment]
@knopers8

**Comment by awegrzyn** [comment]
In travis it'd be simply
```
curl -O https://raw.githubusercontent.com/AliceO2Group/CodingGuidelines/master/_clang-format-4
```

**Comment by Barthelemy** [comment]
Right, I thought of something more complicated but actually you are correct, we can just put in the instructions that people have to wget/download/curl the file from CodingGuidelines. 
I am moving the discussion , which is unrelated to this PR, to JIRA : https://alice.its.cern.ch/jira/browse/O2-351

**Comment by Barthelemy** [comment]
I am merging as I now that there was agreement in WP3 on the rule itself.

**Pull request merged**
