### PR TITLE
Push changes to .clang-format to Common

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
This is my suggestion on how to propagate `.clang-format` to all the other repositories (only `Common` being done here, as an example). This will need a secure variable in the travis configuration, but that's just a couple of clicks. The script could actually validate the contents of `.clang-format` before pushing it.

**Comment by awegrzyn** [comment]
@ktf What happens if branch is protected?

**Comment by ktf** [comment]
Can't we have a token that is allowed to write?

**Comment by ktf** [comment]
Alternatively of course we could use hub and create a PR and merge it manually, in the end we do this once per year or so.

**Comment by awegrzyn** [comment]
Yep both could work

**Comment by awegrzyn** [comment]
Any progress on that? I'd be actually in favour of creating PR instead of committing directly to branch.

**Comment by ktf** [comment]
I was waiting feedback from @dberzano and @barthelemy

**Comment by Barthelemy** [comment]
sorry, will have a look and comment

**Comment by Barthelemy** [comment]
I like the idea. I have no clue about travis but understand what you did (yeah). I agree with Adam that PRs might be neat. At least it makes repo maintainers aware of the change. Do you think it is doable without too much effort ?

**Comment by ktf** [comment]
I can try to cook the PR option. In principle it should be just a matter of adding the `github` gem and use it. If there is consensus (@dberzano ?) I can go ahead and try it.

**Comment by Barthelemy** [comment]
@dberzano ping

**Comment by ktf** [comment]
I did the change which will create a PR rather than pushing directly. It works between `ktf/CodingConvention` and `ktf/Common`. AFAICT, the only thing left is to support different target branches (e.g. dev for AliceO2), but that's trivial.

**Comment by ktf** [comment]
@dberzano ping again

**Comment by ktf** [comment]
I'll take the silence as agreement and I am going to get this to work.

**Pull request merged**
