### PR TITLE
Update coding guidelines for nested namespaces (O2-415)

### PR DESCRIPTION
**Pull request by Barthelemy**
Allow C++17 style nested namespaces.

### CODE REVIEW

**Comment by dberzano** [comment]
This looks good to me, it defines both options and does not enforce one.

**Comment by awegrzyn** [comment]
Looks good, have you investigated whether there's any tool/script that would automatically convert to a new, proposed style?

**Comment by Barthelemy** [comment]
@awegrzyn No I have not. I will have a look. It would be nice, although we could just let it as it is and let people decide whether they want to use the new style (as this is not mandatory). I'll keep you informed.

**Comment by Barthelemy** [comment]
I could not find a tool. I did it by hand for QC : https://github.com/AliceO2Group/QualityControl/pull/130 
With an IDE it did not take much time.

**Comment by Barthelemy** [comment]
Giulio says that clang-tidy 8 could do it . Goot to keep in mind.

**Pull request merged**
